// Endnote .enw tags for importing
export let enwTags = {
  AB: "Abstract",
  AD: "Author Address",
  AN: "Accession Number",
  AU: "Author",
  CL: "Keywords",
  DB: "Name of Database",
  DE: "Keywords",
  DI: "DOI",
  DP: "Database Provider",
  GE: "Keywords",
  IC: "Keywords",
  IL: "Notes",
  IP: "Issue",
  IS: "ISSN",
  JN: "Journal",
  KW: "Keywords",
  LA: "Language",
  PE: "Keywords",
  PG: "Pages",
  PT: "Type of Article",
  PU: "Notes",
  SN: "Notes",
  SO: "Journal (Notes), v. Volume noIssue (Date Year) p. Pages.",
  SU: "Keywords",
  TI: "Title",
  UR: "URL",
  VI: "Volume",
  WB: "URL",
  YR: "Year",
};
