// Endnote .enw tags for importing
export let enwTags = {
  "%A": "Author",
  "%B": "Secondary Title",
  "%C": "Place Published",
  "%D": "Year / Date",
  "%E": "Editor",
  "%F": "Label",
  "%G": "Language",
  "%H": "Translated Author",
  "%I": "Publisher",
  "%J": "Journal / Periodical Name",
  "%K": "Keywords",
  "%L": "Call Number",
  "%M": "Notes",
  "%N": "Issue Number",
  "%P": "Pages",
  "%Q": "Translated Title",
  "%R": "DOI / Electronic Resource",
  "%S": "Series Title",
  "%T": "Title",
  "%U": "URL",
  "%V": "Volume",
  "%X": "Abstract",
  "%Y": "Tertiary Author",
  "%Z": "Custom Field / Notes",
  "%0": "Reference Type",
  "%6": "Number of Volumes",
  "%7": "Edition",
  "%8": "Access Date",
  "%9": "Type of Work",
  "%?": "Subsidiary Author",
  "%@": "ISBN / ISSN",
  "%(": "Original Publication",
  "%>": "Link to PDF",
  "%[": "Access Date",
};
