// Endnote .enw tags for importing
export let enwTags = {
  "%A": "Author",
  "%B": "SecondaryTitle",
  "%C": "PlacePublished",
  "%D": "Date",
  YR: "Year",
  "%E": "Editor",
  "%F": "Label",
  "%G": "Language",
  "%H": "TranslatedAuthor",
  "%I": "Publisher",
  "%J": "Journal/PeriodicalName",
  "%K": "Keywords",
  "%L": "CallNumber",
  "%M": "Notes",
  "%N": "IssueNumber",
  "%P": "Pages",
  "%Q": "TranslatedTitle",
  "%R": "DOI/ElectronicResource",
  "%S": "SeriesTitle",
  "%T": "Title",
  "%U": "URL",
  "%V": "Volume",
  "%X": "Abstract",
  "%Y": "TertiaryAuthor",
  "%Z": "CustomField/Notes",
  "%0": "ReferenceType",
  "%6": "NumberofVolumes",
  "%7": "Edition",
  "%8": "LastUpdateDate",
  "%9": "TypeofWork",
  "%?": "SubsidiaryAuthor",
  "%@": "ISBN/ISSN",
  "%(": "OriginalPublication",
  "%>": "LinktoPDF",
  "%[": "AccessDate",
};
